import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "motion/react";
import confetti from "canvas-confetti";
import { toast, Toaster } from "sonner";
import { 
  Sparkles, 
  FileText, 
  Briefcase, 
  Award, 
  Zap, 
  CheckCircle, 
  ArrowRight, 
  User, 
  Settings,
  BrainCircuit,
  Globe,
  Star,
  ChevronRight
} from "lucide-react";

import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "./components/ui/card";
import { Input } from "./components/ui/input";
import { Textarea } from "./components/ui/textarea";
import { Button } from "./components/ui/button";
import { Label } from "./components/ui/label";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "./components/ui/tabs";

import { BackgroundGlow } from "./components/background-glow";
import { Navbar } from "./components/navbar";
import { FeatureSection, SocialProof } from "./components/features";
import { ResumePreview } from "./components/resume-preview";
import { Testimonials } from "./components/testimonials";

export default function App() {
  const [formData, setFormData] = useState({
    name: "",
    skills: "",
    experience: "",
    title: ""
  });
  const [generatedResume, setGeneratedResume] = useState<any>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [activeTab, setActiveTab] = useState("builder");

  const handleGenerate = async () => {
    if (!formData.name || !formData.skills || !formData.experience) {
      toast.error("Please fill in all required fields!");
      return;
    }

    setIsGenerating(true);
    setActiveTab("preview");
    
    // Simulate complex AI generation
    await new Promise(resolve => setTimeout(resolve, 2500));
    
    const skills = formData.skills.split(',').map(s => s.trim()).filter(s => s);
    const experiences = formData.experience.split('\n').filter(e => e.trim());
    
    setGeneratedResume({
      name: formData.name,
      title: formData.title || "Senior Professional",
      skills: skills,
      experience: experiences,
      email: `${formData.name.toLowerCase().split(' ')[0]}@example.com`,
      phone: "+1 (555) 012-3456",
      location: "San Francisco, CA"
    });
    
    setIsGenerating(false);
    confetti({
      particleCount: 150,
      spread: 70,
      origin: { y: 0.6 },
      colors: ['#4f46e5', '#9333ea', '#6366f1']
    });
    toast.success("Resume successfully generated by AI!");
  };

  return (
    <div className="min-h-screen w-full selection:bg-indigo-100 selection:text-indigo-900" style={{ fontFamily: 'Inter, sans-serif' }}>
      <BackgroundGlow />
      <Navbar />
      <Toaster position="top-center" expand={true} richColors />

      <main className="pt-32 pb-24">
        {/* Hero Section */}
        <section className="max-w-7xl mx-auto px-6 mb-20">
          <div className="flex flex-col lg:flex-row gap-16 items-center">
            {/* Left side: Info */}
            <div className="flex-1 space-y-8">
              <motion.div 
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white/60 backdrop-blur-xl border border-white/80 shadow-sm text-indigo-600 font-semibold text-sm"
              >
                <div className="flex -space-x-1.5">
                  {[1, 2, 3].map(i => (
                    <div key={`hero-avatar-${i}`} className="w-5 h-5 rounded-full border-2 border-white bg-indigo-100" />
                  ))}
                </div>
                <span className="ml-1 tracking-tight">Joined by 2,000+ this month</span>
              </motion.div>

              <motion.h1 
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.1 }}
                className="text-6xl lg:text-7xl font-black text-slate-900 tracking-tighter leading-[0.95]"
              >
                Your career deserves a <span className="bg-gradient-to-r from-indigo-600 to-purple-600 bg-clip-text text-transparent">premium</span> story.
              </motion.h1>

              <motion.p 
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.2 }}
                className="text-xl text-slate-600 max-w-xl leading-relaxed font-medium"
              >
                Stop struggling with templates. Our AI understands your unique impact and translates it into a resume that recruiters can't ignore.
              </motion.p>

              <motion.div 
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.3 }}
                className="flex flex-wrap gap-4 pt-4"
              >
                <div className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-emerald-50 text-emerald-700 font-bold text-sm">
                  <CheckCircle className="w-4 h-4" /> 100% Free to Try
                </div>
                <div className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-blue-50 text-blue-700 font-bold text-sm">
                  <Zap className="w-4 h-4" /> ATS-Optimized
                </div>
                <div className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-purple-50 text-purple-700 font-bold text-sm">
                  <Star className="w-4 h-4" /> 4.9/5 Rating
                </div>
              </motion.div>
            </div>

            {/* Right side: Interactive Form/Preview Container */}
            <div className="flex-1 w-full max-w-2xl">
              <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
                <TabsList className="grid w-full grid-cols-2 mb-8 bg-white/50 backdrop-blur-xl border border-white/60 p-1.5 rounded-2xl h-14 shadow-lg shadow-indigo-100/30">
                  <TabsTrigger 
                    value="builder" 
                    className="rounded-xl data-[state=active]:bg-white data-[state=active]:text-indigo-600 data-[state=active]:shadow-sm font-bold text-[15px] transition-all"
                  >
                    <Settings className="w-4 h-4 mr-2" />
                    Builder
                  </TabsTrigger>
                  <TabsTrigger 
                    value="preview" 
                    className="rounded-xl data-[state=active]:bg-white data-[state=active]:text-indigo-600 data-[state=active]:shadow-sm font-bold text-[15px] transition-all"
                  >
                    <FileText className="w-4 h-4 mr-2" />
                    Preview
                  </TabsTrigger>
                </TabsList>

                <AnimatePresence mode="wait">
                  {activeTab === "builder" ? (
                    <TabsContent value="builder" key="builder-tab" forceMount>
                      <motion.div
                        initial={{ opacity: 0, x: -20 }}
                        animate={{ opacity: 1, x: 0 }}
                        exit={{ opacity: 0, x: 20 }}
                      >
                        <Card className="bg-white/80 backdrop-blur-xl border-white/60 shadow-2xl rounded-[2rem] overflow-hidden border">
                          <div className="absolute top-0 right-0 w-32 h-32 bg-indigo-500/5 blur-3xl -z-10" />
                          <CardHeader className="pb-4">
                            <CardTitle className="text-2xl font-black text-slate-800 flex items-center gap-3">
                              <div className="p-2 bg-indigo-600 rounded-xl">
                                <BrainCircuit className="w-6 h-6 text-white" />
                              </div>
                              Resume Designer
                            </CardTitle>
                            <CardDescription className="text-[15px] font-medium text-slate-500">
                              Our AI will generate your content based on these inputs.
                            </CardDescription>
                          </CardHeader>
                          <CardContent className="space-y-6">
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                              <div className="space-y-2">
                                <Label htmlFor="name" className="text-sm font-bold text-slate-700">Full Name</Label>
                                <div className="relative">
                                  <User className="absolute left-3 top-3 w-4 h-4 text-slate-400" />
                                  <Input 
                                    id="name" 
                                    placeholder="Jane Doe" 
                                    value={formData.name}
                                    onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                                    className="pl-10 h-11 bg-slate-50 border-slate-200 focus:ring-2 focus:ring-indigo-500/20 rounded-xl"
                                  />
                                </div>
                              </div>
                              <div className="space-y-2">
                                <Label htmlFor="title" className="text-sm font-bold text-slate-700">Target Role</Label>
                                <div className="relative">
                                  <Briefcase className="absolute left-3 top-3 w-4 h-4 text-slate-400" />
                                  <Input 
                                    id="title" 
                                    placeholder="Senior Designer" 
                                    value={formData.title}
                                    onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                                    className="pl-10 h-11 bg-slate-50 border-slate-200 focus:ring-2 focus:ring-indigo-500/20 rounded-xl"
                                  />
                                </div>
                              </div>
                            </div>

                            <div className="space-y-2">
                              <Label htmlFor="skills" className="text-sm font-bold text-slate-700">Key Skills (comma separated)</Label>
                              <div className="relative">
                                <Award className="absolute left-3 top-3 w-4 h-4 text-slate-400" />
                                <Input 
                                  id="skills" 
                                  placeholder="React, Figma, Tailwind, Strategy" 
                                  value={formData.skills}
                                  onChange={(e) => setFormData({ ...formData, skills: e.target.value })}
                                  className="pl-10 h-11 bg-slate-50 border-slate-200 focus:ring-2 focus:ring-indigo-500/20 rounded-xl"
                                />
                              </div>
                            </div>

                            <div className="space-y-2">
                              <Label htmlFor="experience" className="text-sm font-bold text-slate-700">Experience Highlights</Label>
                              <Textarea 
                                id="experience" 
                                placeholder="Describe your achievements and roles..." 
                                value={formData.experience}
                                onChange={(e) => setFormData({ ...formData, experience: e.target.value })}
                                className="min-h-[140px] bg-slate-50 border-slate-200 focus:ring-2 focus:ring-indigo-500/20 rounded-xl p-4 leading-relaxed"
                              />
                              <p className="text-xs font-semibold text-slate-400 flex items-center gap-1.5">
                                <Sparkles className="w-3 h-3" /> Tip: Bullet points or paragraphs work great!
                              </p>
                            </div>

                            <Button 
                              onClick={handleGenerate}
                              disabled={isGenerating}
                              className="group relative w-full h-14 rounded-2xl bg-indigo-600 hover:bg-indigo-700 text-white text-lg font-black transition-all shadow-xl shadow-indigo-200 overflow-hidden"
                            >
                              <div className="absolute inset-0 bg-gradient-to-r from-indigo-500 to-purple-600 opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
                              <div className="relative flex items-center justify-center gap-3">
                                {isGenerating ? (
                                  <>
                                    <div className="w-5 h-5 border-3 border-white/30 border-t-white rounded-full animate-spin" />
                                    <span>Brewing AI Magic...</span>
                                  </>
                                ) : (
                                  <>
                                    <Zap className="w-5 h-5 fill-white" />
                                    <span>Generate Resume</span>
                                    <ChevronRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
                                  </>
                                )}
                              </div>
                            </Button>
                          </CardContent>
                        </Card>
                      </motion.div>
                    </TabsContent>
                  ) : (
                    <TabsContent value="preview" key="preview-tab" forceMount>
                      <motion.div
                        initial={{ opacity: 0, scale: 0.95 }}
                        animate={{ opacity: 1, scale: 1 }}
                        exit={{ opacity: 0, scale: 0.95 }}
                      >
                        <ResumePreview data={generatedResume} isGenerating={isGenerating} />
                      </motion.div>
                    </TabsContent>
                  )}
                </AnimatePresence>
              </Tabs>
            </div>
          </div>
        </section>

        <SocialProof />
        <FeatureSection />
        <Testimonials />

        {/* Call to Action */}
        <section className="max-w-7xl mx-auto px-6 mt-12">
          <motion.div 
            initial={{ opacity: 0, scale: 0.95 }}
            whileInView={{ opacity: 1, scale: 1 }}
            viewport={{ once: true }}
            className="p-16 rounded-[3rem] bg-indigo-600 relative overflow-hidden text-center text-white"
          >
            {/* Background pattern */}
            <div className="absolute inset-0 opacity-10 bg-[radial-gradient(#fff_1px,transparent_1px)] [background-size:20px_20px]" />
            <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[800px] h-[300px] bg-white/20 blur-[120px] rounded-full -translate-y-1/2" />
            
            <div className="relative z-10 space-y-8 max-w-3xl mx-auto">
              <h2 className="text-5xl font-black tracking-tighter leading-none">Ready to land your dream role?</h2>
              <p className="text-xl text-indigo-100 font-medium">Join 12,000+ others who stopped struggling with formatting and started getting interviews.</p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <Button size="lg" className="h-16 px-10 rounded-2xl bg-white text-indigo-600 hover:bg-indigo-50 text-xl font-black shadow-2xl">
                  Build My Resume Now
                  <ArrowRight className="w-6 h-6 ml-2" />
                </Button>
                <Button size="lg" variant="outline" className="h-16 px-10 rounded-2xl border-white/30 text-white hover:bg-white/10 text-xl font-bold backdrop-blur-md">
                  Browse Templates
                </Button>
              </div>
              <div className="flex items-center justify-center gap-8 pt-4">
                <div className="flex items-center gap-2"><Globe className="w-5 h-5" /> Used in 120+ countries</div>
                <div className="flex items-center gap-2 text-indigo-200">|</div>
                <div className="flex items-center gap-2"><CheckCircle className="w-5 h-5" /> Secured by AES-256</div>
              </div>
            </div>
          </motion.div>
        </section>
      </main>

      {/* Footer */}
      <footer className="bg-slate-900 pt-24 pb-12 text-slate-400">
        <div className="max-w-7xl mx-auto px-6">
          <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-12 mb-20">
            <div className="col-span-2">
              <div className="flex items-center gap-2 mb-6">
                <div className="w-8 h-8 rounded-lg bg-indigo-600 flex items-center justify-center">
                  <Sparkles className="w-5 h-5 text-white" />
                </div>
                <span className="text-2xl font-black tracking-tight text-white">Resu<span className="text-indigo-400">AI</span></span>
              </div>
              <p className="max-w-xs mb-8 text-[15px] leading-relaxed">
                The most advanced AI resume builder on the market. Craft premium, ATS-optimized resumes in minutes.
              </p>
              <div className="flex gap-4">
                {[1, 2, 3, 4].map(i => (
                  <div key={i} className="w-10 h-10 rounded-xl bg-slate-800 flex items-center justify-center hover:bg-indigo-600 hover:text-white transition-colors cursor-pointer" />
                ))}
              </div>
            </div>
            <div>
              <h4 className="text-white font-bold mb-6 uppercase tracking-wider text-xs">Product</h4>
              <ul className="space-y-4 text-sm font-medium">
                <li className="hover:text-white cursor-pointer transition-colors">Resume Builder</li>
                <li className="hover:text-white cursor-pointer transition-colors">Cover Letter</li>
                <li className="hover:text-white cursor-pointer transition-colors">Pricing</li>
                <li className="hover:text-white cursor-pointer transition-colors">Templates</li>
              </ul>
            </div>
            <div>
              <h4 className="text-white font-bold mb-6 uppercase tracking-wider text-xs">Company</h4>
              <ul className="space-y-4 text-sm font-medium">
                <li className="hover:text-white cursor-pointer transition-colors">About Us</li>
                <li className="hover:text-white cursor-pointer transition-colors">Careers</li>
                <li className="hover:text-white cursor-pointer transition-colors">Privacy</li>
                <li className="hover:text-white cursor-pointer transition-colors">Terms</li>
              </ul>
            </div>
            <div>
              <h4 className="text-white font-bold mb-6 uppercase tracking-wider text-xs">Resources</h4>
              <ul className="space-y-4 text-sm font-medium">
                <li className="hover:text-white cursor-pointer transition-colors">Blog</li>
                <li className="hover:text-white cursor-pointer transition-colors">Help Center</li>
                <li className="hover:text-white cursor-pointer transition-colors">Career Guide</li>
                <li className="hover:text-white cursor-pointer transition-colors">API Docs</li>
              </ul>
            </div>
            <div>
              <h4 className="text-white font-bold mb-6 uppercase tracking-wider text-xs">Social</h4>
              <ul className="space-y-4 text-sm font-medium">
                <li className="hover:text-white cursor-pointer transition-colors">Twitter</li>
                <li className="hover:text-white cursor-pointer transition-colors">LinkedIn</li>
                <li className="hover:text-white cursor-pointer transition-colors">Instagram</li>
                <li className="hover:text-white cursor-pointer transition-colors">Discord</li>
              </ul>
            </div>
          </div>
          <div className="pt-12 border-t border-slate-800 flex flex-col md:flex-row justify-between items-center gap-6 text-sm font-medium">
            <p>© 2026 ResuAI. All rights reserved.</p>
            <div className="flex gap-8">
              <span>Privacy Policy</span>
              <span>Terms of Service</span>
              <span>Cookie Settings</span>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
